apiVersion: v1
kind: Secret
metadata:
  name: cqrs-secret
  namespace: k8s-assign
type: Opaque
stringData:
  MARIADB_HOST: "mariadb-svc.k8s-assign.svc.cluster.local"
  MARIADB_PORT: "3306"
  MARIADB_USER: "user"
  MARIADB_PASSWORD: "password"
  MARIADB_DB: "orders_db"
  MONGO_URI: "mongodb://mongouser:mongopassword@mongo-svc.k8s-assign.svc.cluster.local:27017/orders_read_db?authSource=orders_read_db"
  MONGO_DB: "orders_read_db"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-svc.k8s-assign.svc.cluster.local:9092"
  KAFKA_TOPIC: "order-events"
  PYTHONUNBUFFERED: "1"
