apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: k8s-assign
  labels:
    app: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: juyeon13241/cqrs-fastapi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MARIADB_HOST
          value: "mariadb-svc"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_USER
          value: "user"
        - name: MARIADB_PASSWORD
          value: "password"
        - name: MARIADB_DB
          value: "orders_db"
        - name: MONGO_URI
          value: "mongodb://mongo-svc:27017"
        - name: MONGO_DB
          value: "read_db"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-svc:9092"
        - name: KAFKA_TOPIC
          value: "order-events"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  namespace: k8s-assign
  labels:
    app: fastapi-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: fastapi-app
